#==============================================================================
#D makes all of the .cpp files into .exe files using g++
#==============================================================================

CC = cl
EXT = cpp
CC_OPTS = /EHsc
OBJECTS = *.obj

include $(DROPBOX)/Coding/MakeFiles/all.mk
